# Generated by Django 5.1.6 on 2025-03-12 06:46

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EVChargingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=250)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name="edge",
            old_name="weight",
            new_name="cost",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="geom",
        ),
        migrations.RemoveField(
            model_name="node",
            name="type",
        ),
        migrations.AddField(
            model_name="edge",
            name="geom_way",
            field=django.contrib.gis.db.models.fields.LineStringField(
                default=django.contrib.gis.geos.linestring.LineString(), srid=4326
            ),
        ),
        migrations.AddField(
            model_name="edge",
            name="reverse_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="edge",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges_from",
                to="map.node",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges_to",
                to="map.node",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="geom",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name="node",
            name="name",
            field=models.CharField(default="Unnamed Node", max_length=255),
        ),
    ]
