# Generated by Django 5.1.6 on 2025-03-12 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0002_evcharginglocation_rename_weight_edge_cost_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EVChargingLocation",
        ),
    ]
