# Generated by Django 5.1.6 on 2025-03-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0003_delete_evcharginglocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "type",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=255)),
                ("type_description", models.TextField(default="Описание отсутствует")),
            ],
        ),
        migrations.RenameField(
            model_name="node",
            old_name="status",
            new_name="status_active",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="reverse_cost",
        ),
        migrations.AddField(
            model_name="node",
            name="date_build",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="description",
            field=models.TextField(default="Описание отсутствует"),
        ),
        migrations.CreateModel(
            name="Object_house",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_obj", models.DurationField(blank=True, null=True)),
                ("object_house", models.CharField(max_length=255)),
                ("description_obj", models.TextField(default="Описание отсутствует")),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house",
                        to="map.node",
                    ),
                ),
                (
                    "type_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_types",
                        to="map.type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_description", models.TextField(default="Описание отсутствует")),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="map.edge",
                    ),
                ),
                (
                    "specific",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_links",
                        to="map.type",
                    ),
                ),
            ],
        ),
    ]
