# Generated by Django 5.1.6 on 2025-03-13 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0004_type_rename_status_node_status_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="object_house",
            old_name="date_obj",
            new_name="object_date",
        ),
        migrations.RenameField(
            model_name="object_house",
            old_name="description_obj",
            new_name="object_description",
        ),
        migrations.RenameField(
            model_name="object_house",
            old_name="object_house",
            new_name="object_name",
        ),
        migrations.RenameField(
            model_name="object_house",
            old_name="type_obj",
            new_name="object_type",
        ),
    ]
