# Generated by Django 5.1.6 on 2025-03-13 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0005_rename_date_obj_object_house_object_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="type",
            name="type_name",
        ),
    ]
