# Generated by Django 5.1.6 on 2025-03-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0006_remove_type_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="link_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="map.object_house",
            ),
        ),
    ]
