# Generated by Django 5.1.6 on 2025-03-13 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0007_link_link_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object_house",
            name="object_date",
        ),
    ]
