# Generated by Django 5.1.6 on 2025-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0008_remove_object_house_object_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="object_house",
            name="object_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
