# Generated by Django 5.1.6 on 2025-03-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0009_object_house_object_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object_house",
            name="build",
        ),
        migrations.RemoveField(
            model_name="object_house",
            name="object_type",
        ),
        migrations.CreateModel(
            name="Content_type",
            fields=[
                (
                    "content_type",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "content_type_description",
                    models.TextField(default="Описание отсутствует"),
                ),
                (
                    "content_type_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_from",
                        to="map.type",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Link",
        ),
        migrations.DeleteModel(
            name="Object_house",
        ),
    ]
