# Generated by Django 5.1.6 on 2025-03-20 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0010_remove_object_house_build_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_description", models.TextField(default="Описание отсутствует")),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="map.edge",
                    ),
                ),
                (
                    "link_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_name",
                        to="map.content_type",
                    ),
                ),
                (
                    "specific",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_links",
                        to="map.type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Object_house",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_date",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1500),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Год",
                    ),
                ),
                (
                    "object_description",
                    models.TextField(default="Описание отсутствует"),
                ),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house",
                        to="map.node",
                    ),
                ),
                (
                    "object_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_content_type",
                        to="map.content_type",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_types",
                        to="map.type",
                    ),
                ),
            ],
        ),
    ]
