# Generated by Django 5.1.6 on 2025-03-20 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0011_link_object_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object_house",
            name="object_date",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1500),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Год",
            ),
        ),
    ]
