# Generated by Django 5.1.6 on 2025-03-20 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0012_alter_object_house_object_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="date_build",
        ),
    ]
