# Generated by Django 5.1.6 on 2025-03-20 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0013_remove_node_date_build"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="date_build",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1500),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Год",
            ),
        ),
    ]
